src/config/database/postgresql.py

add exceptio code postgresql.py
---
postgressql.py 에서 DB_URL None에 대한 예외 처리
어떤 변경 사항이 있나요?

feat: Change DB settings

---

.github/workflows/CI.yml

Add CI configuration with PostgreSQL and Redis

---

.github/workflows/CI.yml
migrations/versions/2024_11_13_1614-87c8e0871b16_create_user_table.py
scripts/check.bat

[Fix/CI] Change Env

---

src/app/router/__init__.py
src/app/v1/post/schema/post.py
src/main.py

__init__ 파일에 router를 import 시켜서 한 파일에서 모든 router를 import 가능하게 했습니다.
파이썬 3.1 이상 부터는 Optional보단 | None으로 사용하는게 권장 된다고 하여 변경하였습니다.
어떤 변경 사항이 있나요?

[Feature/post] 타입힌트, import 리팩토링

---

src/app/common/models/tag.py
src/app/v1/comment/entity/comment_tag.py
src/app/v1/user/entity/organization.py

comment_tag 모델 작성
어떤 변경 사항이 있나요?

[feature/tag] comment_tag model 작성

---

src/app/v1/recomment/enitity/recomment.py
src/app/v1/recomment/enitity/recomment_tag.py

recomment 모델 작성
recomment_tag 모델 작성
어떤 변경 사항이 있나요?

[feature/recomment] recomment model 작성

---

.gitignore
src/app/v1/chat/entity/chat_participant.py
src/app/v1/chat/entity/message.py
src/app/v1/chat/entity/room.py
src/main.py

- ChatParticipant, Messages, Rooms
- allow_origin_regex="http://111\\.111\\.111\\.111(:\\d+)?",  
=> 이스케이프 문자 \ 추가 ( \. ->\\. )
- renamed enitity Directory
어떤 변경 사항이 있나요?

[Feature/chat] Add Chat Entities, Fix regex in main.py, Arrange Directory

---

src/app/v1/chat/entity/message.py
src/app/v1/user/entity/student.py
src/app/v1/user/entity/study_group.py
src/app/v1/user/entity/teacher.py
src/app/v1/user/entity/user.py
src/main.py

- window batch 파일 구동 완료
- linux 추가
어떤 변경 사항이 있나요?

[Fix/Feature] Arrange user, chat & Fix/Feature check.bat for windows and Add Linux

---

src/app/v1/chat/entity/room.py

- help_checked(bool) 추가, 선생님에게 속한 학생들 출력 시에 ( Help )표시가 된 채팅방 필요
어떤 변경 사항이 있나요?

[Feature/chat] Add Field in room entity

---

src/app/common/utils/consts.py
src/app/v1/chat/entity/chat_participant.py
src/app/v1/chat/entity/message.py
src/app/v1/chat/entity/room.py
src/main.py
tests/chats/test_chat_model.py
tests/comments/test_comment_model.py
tests/users/test_async_user_model.py
tests/users/test_user_model.py

- type(text, image) 추가
- Chat Test 코드 추가 ( 완료 )
- consts 파일에서 PyEnum -> Enum 변경
- main에서 origin 주소 daesik 제거
- ChatParticipant에서 참고 테이블 이름 정정
- room에서 false import 제거
어떤 변경 사항이 있나요?

[Feature/chat] Add Chat Entity & Chat Test & Refactoring consts, main, etc

---

src/app/v1/chat/entity/message.py
src/app/v1/chat/entity/room.py

- last_message 삭제 ( 불필요 )
- read_checked 추가 ( 메시지 읽기 확인 )
어떤 변경 사항이 있나요?

[Feature/chat] Change Entity

---

.gitignore
migrations/env.py
tests/chats/db_test.py

- 비밀 번호 Encoding 문제로 env.py 에 대해 sqlalchemy.engine.URL.create 메소드를 사용해 자동 Encoding 적용
- 연결 Test 완료
- db 마이그레이션은 서버 내에서 진행할 필요가 있어, ignore
어떤 변경 사항이 있나요?

[Feature/DB] Change DB Connection Setting

---

.github/workflows/CI.yml
src/app/v1/user/entity/user.py

migration은 gitignore되어있네요 알아서 마이그레이션 파일 생성해서 하시면 도비니다
어떤 변경 사항이 있나요?

fix: user entity

---

src/app/router/v1/post.py
src/app/v1/post/repository/post.py

post_id 리턴 값에 추가
어떤 변경 사항이 있나요?

refactor: post_id return add

---

src/app/router/v1/auth.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

login response에 role: teacher or student 추가 했습니다.
어떤 변경 사항이 있나요?

[Feature/login]login role 추가

---

src/app/router/v1/websocket.py
src/app/v1/chat/entity/message.py
src/app/v1/chat/service/room_service.py

Feature/Chat Websocket and Entity

---

docker-compose.yaml
src/app/common/factory.py
src/app/common/utils/verify_password.py
src/app/router/__init__.py
src/app/router/v1/auth.py
src/app/router/v1/chat.py
src/app/router/v1/websocket.py
src/app/v1/chat/entity/participant.py
src/app/v1/chat/entity/room.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py
src/app/v1/user/entity/user.py
src/app/v1/user/schema/requestDto.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py
src/config/database/database_models.py
src/main.py

회원가입시 비밀번호 -> 영문(대소), 숫자, 특수문자 10~20자 이내 로 변경했습니다!
Post /auth/reset/password 
비밀번호 잊어버렸을 때 임시비밀번호 생성(기존 비밀번호 대신 임시 비밀번호를 저장 함)하는 api 추가 생성했습니다.
어떤 변경 사항이 있나요?

[Feature/login]User entity 수정 및 api 추가생성

---

src/app/router/__init__.py
src/app/router/v1/comment.py
src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/schema/requestDto.py
src/app/v1/comment/schema/responseDto.py
src/app/v1/comment/service/comment_service.py
src/main.py

comment 생성,조회,삭제 api
어떤 변경 사항이 있나요?

[feature/comment] 댓글 생성 조회 삭제

---

src/app/v1/comment/entity/comment.py

parent_comment_id 필드 추가
어떤 변경 사항이 있나요?

[feature/recomment] comment entity 수정

---

.gitignore
docker-compose.yaml
src/app/common/utils/dependency.py
src/app/common/utils/image.py
src/app/common/utils/security.py
src/app/router/__init__.py
src/app/router/v1/auth.py
src/app/router/v1/user.py
src/app/v1/comment/entity/comment.py
src/app/v1/user/entity/user.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/schema/requestDto.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py
src/main.py

로그인 -> 학생의 경우 최초 로그인을 했을 때 first_login: True로 response 값을 추가 했습니다.
비밀번호 확인
회원정보 변경 : 교사-> 이메일, 비밀번호, 핸드폰번호
학생-> 이메일, 비밀번호, 핸드폰번호, 학교, 학년
어떤 변경 사항이 있나요?

[Feature/login]최초 로그인 기능 추가

---

src/app/v1/post/repository/post.py

프론트 요구사항 변경에 따른 응답 값 추가
어떤 변경 사항이 있나요?

[Feature/post] 응답값 변경

---

src/app/v1/post/repository/post.py

응답값에 teacher_id 추가
어떤 변경 사항이 있나요?

[Feature/post] teacher 응답에 teacher id 값 추가

---

src/app/common/utils/dependency.py
src/app/router/v1/auth.py
src/app/router/v1/user.py
src/app/v1/user/entity/teacher.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/schema/requestDto.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

[Feature/login]선생님 조회, 학생 최초 로그인 시 선생님 선택 엔드포인트 추가
어떤 변경 사항이 있나요?

[Feature/login]선생님 조회, 학생 최초 로그인 시 선생님 선택 엔드포인트 추가

---

src/app/v1/chat/entity/message.py

- Message Type 변경
- Import 삭제
어떤 변경 사항이 있나요?

[Fix/Chat] Fix Message

---

src/app/v1/post/repository/post.py

[Fix/post] api v1 삭제

---

generate_data/student.py
generate_data/studygroup.py
generate_data/teacher.py
src/app/router/v1/user.py
src/app/v1/auth/schema/responseDto.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/service/user_service.py
src/config/database/postgresql.py
src/main.py

타인 -> 내 프로필 조회 GET /users/profile/{user_id}
회원 탈퇴 -> deactivated_at 필드에 현재 날짜시간 생성 -> deactivated_at 필드값이 not null인 경우 로그인 안 됨
(deactivated_at이후 30일이 지나면 삭제 -> 추후에 스케줄러를 이용해 할 예정)
어떤 변경 사항이 있나요?

[Feature/login] 엔드포인트 생성

---

src/app/common/utils/dependency.py
src/app/router/v1/user.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/service/user_service.py
src/main.py

세션 생성이나 사용 중 예외가 발생하면, 이를 잡아 HTTPException으로 래핑해 500 Internal Server Error를 반환하는 에러 문구 제거
어떤 변경 사항이 있나요?

[Feature/login]에러 문구 제거

---

src/app/router/v1/user.py

GET /users/profile/me 코드 위치 변경 -> 패스 파라미터 경로로 자꾸 인식해서 위치를 변경했습니다.
어떤 변경 사항이 있나요?

[Feature/login]GET /users/profile/me 코드 위치 변경

---

src/main.py

[Feature/Chat] main

---

poetry.lock
pyproject.toml

[Feature/Chat] websockets

---

src/app/common/utils/websocket_manager.py
src/app/router/__init__.py
src/app/router/v1/teacher.py
src/app/router/v1/websocket.py
src/app/v1/chat/entity/message.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/chat.py
src/main.py

[Feature/Chat] many change

---

src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/chat.py

[Feature/Chat] change Time format

---

src/app/v1/chat/entity/message.py
src/app/v1/chat/schema/room_response.py
src/main.py

Add Orgin, Arrange Import

---

src/main.py

change origin

---

src/main.py

[Feature] Add health check Logic

---

src/app/router/v1/chat.py

[Fix/Chat] Fix ask help path

---

src/app/router/v1/chat.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py

[Fix/Chat] Fix Help Response

---

src/app/router/v1/comment.py
src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/service/comment_service.py

mvc패턴으로 리팩토링 했습니다.
어떤 변경 사항이 있나요?

[feature/comment] comment 코드 리팩토링

---

src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/schema/responseDto.py
src/app/v1/comment/service/comment_service.py

응답값에 profile_image 추가했습니다.
어떤 변경 사항이 있나요?

[feature/comment] 응답 값에 profile_image 추가

---

src/app/router/v1/chat.py
src/app/router/v1/websocket.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/schema/websocket_response.py
src/app/v1/chat/service/chat.py
src/app/v1/chat/service/room_service.py

[Feature/Chat] Add get room messages

---

src/app/v1/chat/schema/room_response.py

[Feature/Chat] Add get room messages component

---

src/app/v1/post/repository/post.py

기존 포스트를 작성할때 선생님과 함께했다면 선생님의 정보를 맨 처음 등록된 선생님만을 가져왔었는데
study_group에서 자신이 등록한 선생님 정보를 토대로 가져오개 변경함
어떤 변경 사항이 있나요?

[Refactor/post] teacher 수정

---

src/app/v1/chat/entity/participant.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py

[Feature/Chat] Add profile_images

---

src/app/router/v1/auth.py
src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/schema/requestDto.py
src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/schema/requestDto.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

소셜로그인 기능 추가 (kakao,naver,google) 및 이메일 전화번호 저장
추가 회원정보 업데이트 기능은 조금 더 보강해야 함
어떤 변경 사항이 있나요?

[Feature/login]소셜로그인 기능 추가

---

src/app/router/v1/auth.py

[Feature/login]엔드포인트 변경

---

src/app/router/v1/chat.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py

[Feature/Chat] Add Nickname

---

src/app/router/v1/auth.py

소셜 로그인 엔드포인트 수정
어떤 변경 사항이 있나요?

[Feature/login]엔드포인트 수정

---

src/app/router/v1/auth.py

Feature/chat Login

---

src/app/router/v1/auth.py
src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py
src/main.py

[Feature/login]콜백 response 변경

---

src/app/common/utils/websocket_manager.py
src/app/router/v1/chat.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py
src/main.py

[Feature/Chat] Fix CORS, Add Endpoint Students room

---

src/app/router/v1/comment.py
src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/service/comment_service.py

post_id 데이터 타입 int 에서 str로 변경했습니다.
어떤 변경 사항이 있나요?
어떤 변경 사항이 있나요?

[feature/comment] post_id 타입 변경

---

src/app/router/v1/comment.py
src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/schema/responseDto.py
src/app/v1/comment/service/comment_service.py

post_id, user_id 응답값 external_id 로 변경
어떤 변경 사항이 있나요?

[feature/comment] comment 응답값 변경

---

src/app/common/utils/security.py
src/app/common/utils/websocket_manager.py
src/app/router/v1/websocket.py
src/app/v1/user/schema/responseDto.py
src/config/database/mongo.py

Fix Websocket

---

src/app/v1/user/service/user_service.py

타인 -> 프로필 조회 수정
어떤 변경 사항이 있나요?

[Feature/users]타인-> 프로필 조회 수정

---

src/app/v1/post/repository/post.py

Fix Post_1

---

src/app/router/v1/user.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/service/user_service.py

[Feature/users]프로필 변경 코드 수정

---

generate_data/student.py
generate_data/teacher.py
src/app/common/utils/verify_password.py
src/app/router/v1/auth.py
src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/service/oauth_service.py

소셜로그인-> 비밀번호 암호화
어떤 변경 사항이 있나요?

[Feature/users]소셜로그인-> 비밀번호 암호화

---

src/app/v1/post/repository/post.py

fix: user수정

---

src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/service/comment_service.py

- 댓글 생성 시 post 테이블의 comment_count를 증가시키는 로직 추가
- 댓글 삭제 시 comment_count를 감소시키는 로직 추가
- 대댓글은 comment_count에 포함되지 않도록 처리
어떤 변경 사항이 있나요?

[feature/comment] comment_count 업데이트 로직 추가 

---

src/app/common/utils/image.py
src/app/router/v1/auth.py
src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/service/oauth_service.py
src/app/v1/user/service/user_service.py

프로필 이미지 변경 로직 수정
어떤 변경 사항이 있나요?

[Feature/users]프로필 이미지 변경 로직 수정

---

src/app/router/v1/auth.py
src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/schema/requestDto.py
src/app/v1/auth/service/oauth_service.py

소셜로그인 전화번호 None 일 때 무작위 추가
어떤 변경 사항이 있나요?

[Feature/users]소셜로그인 전화번호 추가

---

src/app/router/v1/auth.py
src/app/v1/auth/service/oauth_service.py

[Feature/users]회원정보 반환 값 변경

---

src/app/v1/user/repository/user_repository.py

프로필 조회 시 게시글 내림차순으로 정렬
어떤 변경 사항이 있나요?

[Feature/users]게시글 내림차순으로 정렬

---

src/app/v1/auth/repository/oauth_repository.py

[Feature/users]회원정보추가 에러코드 수정

---

src/app/v1/user/repository/user_repository.py

[Feature/users]게시글 순서 변경

---

src/app/v1/user/repository/user_repository.py

[Feature/users]게시글이미지 순서 변경

---

src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py

[Feature/users]추가회원정보 반환값 변경

---

src/app/v1/comment/repository/comment_repo.py
src/app/v1/comment/schema/responseDto.py
src/app/v1/comment/service/comment_service.py
src/app/v1/post/schema/post.py

user_id 응답 값 id 값으로 변경
어떤 변경 사항이 있나요?

[fix/comment] user_id 응닫값 변경

---

src/app/v1/user/schema/requestDto.py

[Feautre/users]프로필 수정 로직 변경

---

src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py
src/app/v1/user/schema/requestDto.py
src/app/v1/user/service/user_service.py

[Feature/users]프로필 수정 로직 변경

---

src/app/router/v1/auth.py
src/app/v1/auth/repository/oauth_repository.py
src/app/v1/auth/schema/responseDto.py

[Feature/users]소셜로그인 그룹로직 추가

---

src/app/common/utils/websocket_manager.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/user/schema/requestDto.py

Feature/Chat Message init

---

src/app/router/v1/auth.py
src/app/router/v1/user.py
src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py
src/app/v1/user/repository/user_repository.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

[Feature/users]study_group 추가

---

src/app/common/utils/verify_password.py
src/app/v1/user/service/user_service.py

[Feature/users]비밀번호 범위 수정

---

poetry.lock
pyproject.toml
src/app/common/utils/websocket_manager.py
src/app/router/v1/websocket.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/service/room_service.py
src/config/database/redis.py

[Feature/chat] Websocket Update

---

src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

[Feature/users]프로필 조회 반환값 변경

---

src/app/router/v1/user.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

타인 -> 내 프로필 조회 반환값 변경
어떤 변경 사항이 있나요?

[Feature/users]타인 -> 내 프로필 조회 반환값 변경

---

src/app/common/utils/websocket_manager.py

Feature/Chat Websocket Update

---

src/app/common/utils/websocket_manager.py
src/app/v1/chat/repository/room_repository.py
src/app/v1/chat/service/room_service.py

Feature/chat Websocket

---

src/app/v1/post/repository/post.py

refactor: 하드코드 수정

---

src/app/v1/post/repository/post.py

refactor: pagination 수정

---

src/app/common/utils/websocket_manager.py
src/app/router/v1/websocket.py
src/app/v1/chat/schema/room_response.py
src/app/v1/chat/service/room_service.py
src/main.py

Feature/chat Room Pagenation

---

src/app/v1/auth/schema/responseDto.py
src/app/v1/auth/service/oauth_service.py
src/app/v1/user/schema/responseDto.py
src/app/v1/user/service/user_service.py

테스트용 refresh token 반환값에서 제거
어떤 변경 사항이 있나요?

[Feature/users]refresh token 반환값에서 제거

---

.github/workflows/CD.yml
.github/workflows/CI.yml
src/app/v1/comment/service/comment_service.py

[Feature/users]CI.yml 수정

---

src/app/router/v1/post.py
src/app/v1/post/repository/post.py

refactor: 요구사항 변경 리스폰스 데이터 추가

---

src/app/router/v1/post.py
src/app/v1/post/repository/post.py
src/app/v1/post/service/post.py

feat: 프론트 요구사항 추가

---

src/app/router/v1/websocket.py

Feature/Chat add Image in chat

---

src/main.py

Feature/Chat Main

---

src/app/v1/comment/service/comment_service.py

[fix/recomment] 대댓글 응답값 수정

---

.github/workflows/CD.yml
.github/workflows/CI.yml
src/config/database/postgresql.py
src/main.py

Feature/chat CI 

---

.github/workflows/CD.yml

Feature/Chat CI user

---

.github/workflows/CD.yml

Feature/Chat CI container name

---

.github/workflows/CD.yml

Feature/Chat CI container

---

poetry.lock
pyproject.toml

Feature/Chat CI gunicorn

---

src/app/common/utils/redis_utils.py
src/app/v1/user/service/user_service.py

- Redis 서버 변경
- Refresh Token 정보 코드 변경
어떤 변경 사항이 있나요?

Refactor/Auth Change Redis Server & Refactoring refresh token in user_service

---

src/config/database/postgresql.py
src/main.py

Fix Remove DB debug mode & Health Check for about Kong

---

README.md
generate_data/student.py
infra/nginx.conf
src/app/common/utils/redis_utils.py
src/main.py

Fix Many Things

---

src/main.py

Feature - Readme Upload_1

---

README.md

Feature - Readme Upload_2

---

README.md
src/app/common/utils/websocket_manager.py

Refactor/Chat - Block AI, Modify README Line
